export const OPEN_WINDOW_NEW_OBJ = "ADD_OBJECT/OPEN_WINDOW_NEW_OBJ"
export const SAVE_TO_STORE_INPUT_NAME = "ADD_OBJECT/SAVE_TO_STORE_INPUT_NAME"
export const SAVE_TO_STORE_INPUT_FILE_PVO = "ADD_OBJECT/SAVE_TO_STORE_INPUT_FILE_PVO"
export const SAVE_TO_STORE_INPUT_FILE_RP = "ADD_OBJECT/SAVE_TO_STORE_INPUT_FILE_RP"